
export const mockBLData = [
  { 
    id: "1", 
    blNumber: "BL001", 
    date: "2023-05-10", 
    shipper: "Ahmed Mohammad", 
    shipperAddress: "P.O. Box 123, Doha, Qatar",
    consignee: "Sri Lankan Cargo", 
    consigneeAddress: "123 Main St, Colombo, Sri Lanka",
    notifyParty: "Sri Lankan Customs",
    notifyPartyAddress: "456 Port Road, Colombo, Sri Lanka",
    origin: "Doha", 
    destination: "Colombo",
    cargoType: "Personal Effects",
    vessel: "MSC Gülsün",
    voyageNo: "QA235",
    loadingPort: "Doha Port",
    dischargePort: "Colombo Port",
    grossWeight: "500",
    netWeight: "450",
    measurement: "3.5",
    packages: "10",
    marksAndNumbers: "SHLC001-010",
    goodsDescription: "Used household items and personal effects",
    containerNo: "MSDU1234567",
    sealNo: "SL9876543",
    status: "Shipped",
    shippingMarks: "Handle with care",
    freightCharges: "Prepaid",
    placeOfIssue: "Doha, Qatar",
    dateOfIssue: "2023-05-08",
  },
  { 
    id: "2", 
    blNumber: "BL002", 
    date: "2023-06-15", 
    shipper: "Mohammed Ali", 
    shipperAddress: "P.O. Box 456, Doha, Qatar",
    consignee: "Tunisian Cargo Services", 
    consigneeAddress: "25 Port Avenue, Tunis, Tunisia",
    notifyParty: "Tunisian Customs Authority",
    notifyPartyAddress: "12 Harbor Road, Tunis, Tunisia",
    origin: "Doha", 
    destination: "Tunis",
    cargoType: "Car",
    vessel: "CMA CGM Antoine",
    voyageNo: "QT127",
    loadingPort: "Doha Port",
    dischargePort: "Tunis Port",
    grossWeight: "1250",
    netWeight: "1150",
    measurement: "15.0",
    packages: "1",
    marksAndNumbers: "TNCS001",
    goodsDescription: "Toyota Land Cruiser 2020, White, VIN: JT3DJ81W0Y420",
    containerNo: "CMAU1987654",
    sealNo: "TN7654321",
    status: "In Transit",
    shippingMarks: "Vehicle - Fragile",
    freightCharges: "Prepaid",
    placeOfIssue: "Doha, Qatar",
    dateOfIssue: "2023-06-10",
  },
];
