
import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import Layout from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { ArrowLeft, Save, UserPlus } from "lucide-react";
import { motion } from "framer-motion";
import { supabase } from "@/integrations/supabase/client";

const SalesRepForm = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    title: "Mr.",
    name: "",
    employeeNumber: "",
    operation: "UPB - SYSTEM",
    available: "Y",
    country: "Qatar",
  });
  
  // Load existing sales rep data if editing
  useEffect(() => {
    if (id) {
      const loadRep = async () => {
        const { data, error } = await supabase
          .from('sales_representatives')
          .select('*')
          .eq('id', id)
          .maybeSingle();
        if (data) {
          setFormData({
            title: (data as any).title || "Mr.",
            name: data.name,
            employeeNumber: (data as any).employee_number || "",
            operation: (data as any).operation || "UPB - SYSTEM",
            available: data.is_active ? "Y" : "N",
            country: data.country || "Qatar",
          });
        }
        if (error) {
          console.error("Failed to load sales rep:", error);
          toast.error("Failed to load sales representative");
        }
      };
      loadRep();
    }
  }, [id]);
  
  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData({ ...formData, [name]: value });
  };
  
  const handleSave = async () => {
    if (!formData.name.trim()) {
      toast.error("Please enter a name");
      return;
    }
    
    setLoading(true);
    try {
      if (id) {
        // Update existing
        const { error } = await supabase
          .from('sales_representatives')
          .update({
            name: formData.name,
            is_active: formData.available === "Y",
            country: formData.country,
            title: formData.title,
            operation: formData.operation,
          } as any)
          .eq('id', id);
        if (error) throw error;
      } else {
        // Insert new — employee_number auto-generated by trigger
        const { error } = await supabase
          .from('sales_representatives')
          .insert({
            name: formData.name,
            is_active: formData.available === "Y",
            country: formData.country,
            title: formData.title,
            operation: formData.operation,
          } as any);
        if (error) throw error;
      }
      
      toast.success("Sales representative saved successfully");
      navigate("/master/salesrep/list");
    } catch (error: any) {
      console.error("Error saving sales rep:", error);
      toast.error("Failed to save sales representative: " + error.message);
    } finally {
      setLoading(false);
    }
  };
  
  return (
    <Layout title="Add Sales Representative">
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
        className="bg-white rounded-lg shadow-sm border border-gray-200 animate-fade-in"
      >
        <div className="p-4 bg-gradient-to-r from-green-50 to-emerald-50 border-b border-green-100">
          <h3 className="text-lg font-medium text-green-800 flex items-center">
            <UserPlus className="mr-2 h-5 w-5 text-green-700" />
            {id ? "Update" : "Add"} Sales Representative
          </h3>
        </div>
        
        <div className="p-6">
          <div className="grid grid-cols-1 gap-6 max-w-3xl">
            <motion.div
              className="grid grid-cols-4 gap-3 items-end"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.1 }}
            >
              <div className="col-span-1">
                <label className="text-sm font-medium mb-1 block">TITLE:</label>
                <select
                  name="title"
                  value={formData.title}
                  onChange={handleInputChange}
                  className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                >
                  <option value="Mr.">Mr.</option>
                  <option value="Mrs.">Mrs.</option>
                  <option value="Ms.">Ms.</option>
                  <option value="Dr.">Dr.</option>
                </select>
              </div>
              <div className="col-span-3">
                <label className="text-sm font-medium mb-1 block">NAME:</label>
                <Input 
                  name="name"
                  value={formData.name}
                  onChange={handleInputChange}
                  className="border border-gray-300 transition-colors focus:border-green-400"
                  placeholder="Enter name"
                />
              </div>
            </motion.div>
            
            <motion.div
              className="flex flex-col"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.2 }}
            >
              <label className="text-sm font-medium mb-1">EMPLOYEE NUMBER:</label>
              <Input 
                name="employeeNumber"
                value={formData.employeeNumber || (id ? '' : 'Auto-generated on save')}
                className="border border-gray-300 transition-colors focus:border-green-400 bg-blue-50"
                placeholder="Auto-generated"
                readOnly
              />
              <p className="text-xs text-blue-600 mt-1">
                Employee number is auto-generated by the system
              </p>
            </motion.div>

            <motion.div
              className="flex flex-col"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.25 }}
            >
              <label className="text-sm font-medium mb-1">COUNTRY:</label>
              <select
                name="country"
                value={formData.country}
                onChange={handleInputChange}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
              >
                <option value="Qatar">Qatar</option>
                <option value="Sri Lanka">Sri Lanka</option>
                <option value="Kenya">Kenya</option>
                <option value="Sudan">Sudan</option>
                <option value="Tunisia">Tunisia</option>
                <option value="Saudi Arabia">Saudi Arabia</option>
              </select>
            </motion.div>
            
            <motion.div
              className="flex flex-col"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.3 }}
            >
              <label className="text-sm font-medium mb-1">OPERATION:</label>
              <select
                name="operation"
                value={formData.operation}
                onChange={handleInputChange}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
              >
                <option value="UPB - SYSTEM">UPB - SYSTEM</option>
                <option value="ICG">ICG</option>
                <option value="OTHER">OTHER</option>
              </select>
            </motion.div>
            
            <motion.div
              className="flex flex-col"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.4 }}
            >
              <label className="text-sm font-medium mb-1">AVAILABLE:</label>
              <select
                name="available"
                value={formData.available}
                onChange={handleInputChange}
                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
              >
                <option value="Y">Y</option>
                <option value="N">N</option>
              </select>
            </motion.div>
          </div>
          
          <div className="mt-8 flex gap-3">
            <Button 
              onClick={handleSave}
              disabled={loading}
              className="bg-green-600 hover:bg-green-700 transition-colors hover:scale-105 transform duration-200 flex items-center"
            >
              <Save className="mr-2 h-4 w-4" />
              {loading ? 'Saving...' : 'Save'}
            </Button>
            <Button 
              onClick={() => navigate("/master/salesrep/list")}
              variant="outline"
              className="border-gray-300 transition-colors hover:border-green-400 flex items-center"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Go Back
            </Button>
          </div>
        </div>
      </motion.div>
    </Layout>
  );
};

export default SalesRepForm;
