
export const COMMON_ITEMS = [
  "LARGE CARTON BOX PERSONAL EFFECTS",
  "MEDIUM CARTON BOX PERSONAL EFFECTS",
  "SMALL CARTON BOX PERSONAL EFFECTS",
  "SUITCASE PERSONAL EFFECTS",
  "TRUNK PERSONAL EFFECTS",
  "FURNITURE - TABLE",
  "FURNITURE - BED",
  "FURNITURE - CHAIR",
  "FURNITURE - SOFA",
  "FURNITURE - CABINET",
  "FURNITURE - CHEST OF DRAWERS",
  "ELECTRONIC - TELEVISION",
  "ELECTRONIC - REFRIGERATOR",
  "ELECTRONIC - WASHING MACHINE",
  "ELECTRONIC - AIR CONDITIONER",
  "ELECTRONIC - COMPUTER",
  "KITCHEN - MICROWAVE",
  "KITCHEN - COOKWARE SET",
  "KITCHEN - DISHWARE SET",
  "MISCELLANEOUS GOODS"
];
