// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knuurhysrqfbeodlvjjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtudXVyaHlzcnFmYmVvZGx2amp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDIwNTEsImV4cCI6MjA2NzIxODA1MX0.Oo7f-toz0NnmeD6ZXJib9yNzpPEflptmkLSP2CudFTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});